name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - Python Tests
    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Deploy through AWS Systems Manager
        env:
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |

          set -e

          echo "Sending deployment command to EC2..."

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "set -e",
              "cd /home/ec2-user/devops-task-manager",
              "echo Pulling latest code...",
              "git pull origin main",
              "echo Deploying application...",
              "docker compose -f docker-compose.prod.yml up -d --build",
              "echo Cleaning unused Docker images...",
              "docker image prune -f",
              "echo Deployment status:",
              "docker compose -f docker-compose.prod.yml ps",
              "echo Checking application health...",
              "curl -f http://localhost/system/health"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          echo "Waiting for deployment..."

          aws ssm wait command-executed \
            --instance-id "$INSTANCE_ID" \
            --command-id "$COMMAND_ID"

          echo "Deployment result:"

          aws ssm get-command-invocation \
            --instance-id "$INSTANCE_ID" \
            --command-id "$COMMAND_ID" \
            --query '{
              Status: Status,
              Output: StandardOutputContent,
              Error: StandardErrorContent
            }' \
            --output json
