name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  pull_request:
    paths:
      - "terraform/**"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
    outputs:
      changes: ${{ steps.plan.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.1"

      - name: Terraform Version
        run: terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::689505268101:role/GitHubActions-Terraform
          aws-region: ap-south-1
          role-session-name: GitHubActionsTerraformPlan

      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json
          CHANGES=$(jq '[.resource_changes[] | select(.change.actions != ["no-op"])] | length' plan.json)
          echo "Real resource changes detected: $CHANGES"
          echo "exitcode=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Upload plan artifact
        if: steps.plan.outputs.exitcode != '0'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    if: needs.plan.outputs.changes != '0' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.1"

      - name: Terraform Version
        run: terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::689505268101:role/GitHubActions-Terraform
          aws-region: ap-south-1
          role-session-name: GitHubActionsTerraformApply

      - run: terraform init

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
